eggheadio-github/stack-overflow-copy-paste

src/index.js, src/random-integer.js, test/random-integer.test.js
To close #13 , I add a function that return an integer between min and max input. The test make sure
that the result won't be lower than min input and won't be greater than max input.
#13
=> feat(randomInteger): Add randomInteger with tests

src/index.js, src/sort-objects-array.js, test/sort-objects-array.test.js
Getting eslint errors on all the other files in src
Is it because I am on Windows?
I am not getting them on test/sort-objects-array.test.js and src/sort-objects-array.js because I changed my editor to use LF.
What should I do?
=> WIP: Getting eslint errors because of linebreaks

src/index.js, src/object-values-to-string.js, test/object-values-to-string.test.js
To close #33: I've added a function that takes in parameter an object and returns a comma-separated
string that is composed of all its values. The tests make sure the value passed is really an object
and that its undefined or null properties are skipped
#33
=> feat(objectValuesToString): add 'objectValuesToString' method with tests

.gitignore, package.json, src/get-object-size.js, src/index.js, test/get-object-size.test.js
Hey, for some reason, I was trying to finalize this with `npm run commit` and ended up getting some errors.
I made a gist of the error output here:
https://gist.github.com/mtheoryx/ba3155ea1f68af015221be480d4f7452
And here is the npm-debug.log output:
https://gist.github.com/mtheoryx/81b75de88293152203424bd837568340
Any thoughts on what may be going on?
I uninstalled eslint globally (I had that for another project), and also deleted the node_modules directory and ran `npm install` just in case with the same result.
Cheers, appreciate any guidance!
=> WIP: Cannot get npm run commit to run due to some npm errors

src/index.js, src/validateEmail.js, test/validateEmail.js
Hi,
So I was implementing the validate email id using the stackoverflow regex , http://stackoverflow.com/questions/46155
And it failed during the commit because the line was too long , so I used another answer from stackoverflow to break the regex into multiple lines.
http://stackoverflow.com/questions/12317049
Now the lint tool started complaining about unnecessary escape characters. When I removed them to finally pass the tests, the actual validation regex stopped working .
Any help would be greatly appreciated. 
Regards
Anup
=> WIP: Cannot get lint to pass without breaking the regex

src/index.js, src/is-null-or-whitespace.js, test/is-null-or-whitespace.test.js
Here's a PR for [#45](https://github.com/eggheadio-github/stack-overflow-copy-paste/issues/45).
=> feat(isNullOrWhitespace): Add isNullOrWhitespace function

src/index.js, src/startsWith.js, test/startsWith.test.js
First PR, hope it fits the guidelines.
Closes #49
=> feat: Add startsWith function

src/index.js, src/remove-duplicates.js, test/remove-duplicates.test.js
=> feat(removeDuplicates): Add removeDuplicates function

test/flatten.test.js
My first PR. Nothing special just add a new test for the new implementation of flatten.
=> test: Add a test for deep flatten

src/index.js, src/subtract.js, test/subtract-test.js
I am adding a 'subtract' function. This is my first pull request. Thank you @kentcdodds, for your tutorials.
=> feat(subtract): Add a "subtract" function

src/index.js, src/multiply.js, test/multiply.test.js
Add a function to multiply two numbers: num1 and num2.
Closes issue #57.
I just found Javascript Air and miss it already. On the plus side this way I will be able to go through the whole ouvre :). Thanks for everything you do that builds and supports this community @kentcdodds.
Flattery out of the way, I hope this PR goes ok :)
=> feat: Add a 'multiply' function

src/index.js, src/pad-left.js, src/sum.js, test/pad-left.test.js, test/sum.test.js
Hi Kent,
I am trying to submit my first PR, but I am having trouble with the hooks it seems. I am still working on figuring out some of the expressions that are missing when I am committing, but can I check with you with the overall intention of the PR? 
Essentially I am adding a basic reduce function to add up all the numbers in an array; SO base is found [here](http://stackoverflow.com/questions/1230233/how-to-find-the-sum-of-an-array-of-numbers).
Here is the code that I am proposing:
```
function sum(arr) {
return arr.reduce(function(a, b) {
return a + b }, 0)
}
```
Do you think it is an acceptable code? Thanks,
=> add sum to add all elements in array

src/dec2bin.js, src/index.js, test/dec2bin.test.js
As mentioned in the docblock comment it only works with positive integers, and I haven't tested with very large numbers i.e. those greater than 32-bit.
=> dec2bin function - converts decimal number to binary

src/index.js, src/is-today.js, test/is-today.test.js
First of all, congratulations on this repo. It's a great way to learn the required workflow to start contributing to open source projects.
This pull request aims to:
* Add function that tests if a given date is equal to today
Closes #71
=> feat(isToday): add isToday function

src/index.js, src/search-and-replace.js, test/search-and-replace.test.js
Hi,i made this pull request based on this issue #74 , can you give your feedback on what should i change?
=> My First pull request

src/index.js, src/reduce-to-tally.js, test/reduce-to-tally.test.js
=> feat(reduce): reduce functionality

src/index.js, src/init-array.js, test/init-array.test.js
Hi,
How can I get the code coverage to run?
I'm working with "npm run test:watch", but its green even though I did not add any tests.
I DID get a coverage error when trying to commit, but wanted to collaborate on the PR to get the hang of it :)
Thanks!
=> WIP: how to run code coverage?

src/index.js, src/to-power.js, test/to-power.test.js
Closes #80
Hi Kent, I'm hoping this pull request looks goo, let me know if it needs any more tests, or I need to change anything. Thanks!
Great project by the way, the egghead course for this was great!
=> feat(toPower): Add toPower function

src/index.js, src/mod.js, test/mod.test.js
Hi, I believe this is correct. If anything looks wrong just let me know. Thanks!
Closes #86
=> feat(mod): Add mod function (#86)

src/index.js, src/swap-case.js, test/swap-case.test.js
Add a function to change uppercase to lowercase letters and vice-versa for a given string.
=> feat(swapCase): add a swapCase function

src/index.js, src/shallow-equal.js, test/shallow-equal.test.js
Hey! Great project and great tutorial. I want to contribute by adding shallowEqual function to shallow compare two objects, but I'm having problems with passing the test coverage threshold. Can you point me to the problem with my tests? Thanks!
=> WIP: Cannot meet branches coverage

src/endsWith.js, src/index.js, test/endsWith.test.js
Hey Kent, checkout my pull request.
Add a function that checks if a string ends with a given input
Closes #90
=> feat(endsWith): add endsWith function (#90)

src/index.js, src/round.js, test/round.test.js
=> feat(round): function for simple decimal rounding

src/checkPalindrome.js, src/index.js, test/checkPalindrome.test.js
This function removes all non-alphanumeric characters and spaces and then checks to see if the
string is a palindrome
=> feat: Add function to see if string is palindrome

src/index.js, src/revstring.js, test/revstring.test.js
=> feat(revstring): Add revstring function

src/cube.js, src/index.js, test/cube.test.js
Add a function to find the cube of a number.
=> feat(cube): Add cube function

src/index.js, src/slugify.js, test/slugify.test.js
A function to slugify text input, trims whitespaces and multiple dashes
Closes #120
=> feat(slugify): Add a slugify function

src/convertToRoman.js, src/index.js, test/convertToRoman.test.js
Here's my 'convertToRoman' function.
Hope everything is ok.
=> feat(convertToRoman): Add 'convertToRoman' function (#122)

src/gcd.js, src/index.js, test/gcd.test.js
Hi! I added gcd function to the project. 
The issue for this PR #124. 
The original solution code can be found here https://stackoverflow.com/questions/17445231/js-how-to-find-the-greatest-common-divisor
=> WIP(gcd): Add gcd function

src/contains.js, src/index.js, test/contains.test.js, test/hex2rgb.test.js
Thanks for the hard work Ken. All suggestions are welcomed.
=> feat(contains): Add contains function

src/flatten.js
One of my firsts github conributions.
=> WIP: Contribution

src/array-median.js, src/index.js, test/array-median.test.js
Added a function to find the median value of an unsorted array with numeric values. 
It rejects parameters that:
- aren't array
- include nonnumeric items
- have a length of 0
If these cases pass, it sorts the given array and calculates the median.
=> feat(median): Add median function

src/convert-first-letter-to-capital.js, src/index.js, test/convert-first-letter-to-capital.test.js
When i wrote my commit message trying to push and make a pull request I was getting a lot of errors with the git hooks. I need help with this thank you. 
Below is what it looks like in my console bear with me:
```
C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste>git commit -m "feat(capitalizeFirstLetter): add 'capitalizeFirstLetter'function #142
> stack-overflow-copy-paste@0.0.0-semantically-released validate C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-overflow-copy-paste\stack-overflow-copy-paste
> npm-run-all lint test build
> stack-overflow-copy-paste@0.0.0-semantically-released lint C:\Users\oyin-k.saintscommunity\Documents\Work\coding\Projects\OSS\eggheadio-stack-over …
```
=> WIP: Need help not passing with the git hooks, throwing of npm errors

src/index.js, src/remove-falsy.js, test/remove-falsy.test.js
=> feat(removeFalsy): add removeFalsy function and tests

src/index.js, src/swapElements.js, test/swapElements.test.js
This is a completely new feature for broadening API. The swapElements(x, y, target) swaps two elements at a given array target at specified indexes x and y. There are also a test file for this function which can be found in tests/swapElements.test.js.
=> feat(*): add swapElements function

src/index.js, src/remove-accents.js, test/remove-accents.test.js
Implements method to remove accentuated characters from a string. Based
on: https://stackoverflow.com/a/37511463/2002514
Closes #161
=> feat(removeAccents): add removeAccents functions with test

src/multiply.js, src/startsWith.js, src/subtract.js
bollean > boolean
2 white space > 1 white space
=> feat(common): Fix wrong word and white space

.editorconfig, src/index.js, src/removeElementFromArray.js, test/removeElementFromArray.test.js
I have added the js file, test file and modified the index.js accordingly, I don't know what to do next. 
What does it mean by 'coverage' here?
=> WIP: Cannot get coverage quite there

src/index.js, src/tail.js, test/tail.test.js
Add tail function that returns all but the first element of array.
* Return [] for null and undefined
Closes #176
=> feat(tail): add tail function

src/index.js, src/makeObjectIterable.js, test/makeObjectIterable.test.js
- Code coverage is 100%
- I am not sure if this is the best implementation of tests for `makeObjectIterable`. Any suggestions to make it better?
=> feat(makeObjectIterable): Add makeObjectIterable function

package.json, src/index.js, src/lcm.js, test/lcm.test.js
For example,
An input of 12 and 5 would return 60.
=> Add LCM function

src/index.js, src/occurrences.js, test/occurrences.test.js
Making my first pull request: add occurrences function.
=> feat(occurrences): add occurrences function with tests

src/debounce.js, src/index.js, test/debounce.test.js
Added a debounce function to prevent multiple function calls at a time
#190
=> feat(debounce): add 'debounce' function

src/curry.js, src/index.js, test/curry.test.js
I have added a new utility function that allows for the creation of a curried version of a function provided. I also added a basic test to verify that the function behaves as expected.
Resolves [#193](https://github.com/eggheadio-github/stack-overflow-copy-paste/issues/193)
=> feat(curry): add curry function with tests

src/index.js, src/removeProperty.js, test/removeProperty.test.js
Let me know if the single test is enough.  Thanks again for the great tutorial.
=> feat(removeProperty): add function removeProperty with test

src/index.js, src/last.js, test/last.test.js
=> feat(last): add last function

src/descending-order.js, src/index.js, test/array-average.test.js, test/descending-order.test.js
Thanks once again for taking the time to create and maintain this project.
=> feat(descendingOrder): add descendingOrder function

src/BitwiseAnd.js, src/index.js, test/BitwiseAnd.test.js
=> feat(BitwiseAnd): Add BitwiseAnd function

src/index.js, src/timeSince.js, test/timeSince.test.js
Hey Kent, I implemented the function and wrote the tests to #215 
Thanks for helping me make my first pr! You're truly doing god's work!!!
here's your gif <3
=> feat(timeSince): time elapsed since in xx days/hours/minutes ago format

src/first.js, src/index.js, test/first.test.js
=> This function will return the first element of the array

src/index.js, src/rollDice.js, test/rollDice.test.js
Returns a value between 1 and 6
none
=> feat(NA): Simulates roll of a die

src/index.js, src/numberToString.js, test/numberToString.test.js
Hi KCD,
I'm a first time committer inspired by one of your egghead lessons ;) I tried to follow the guideline as much as possible. I got the coverage to 100% but the tests are rather on the weak side :(
Also, eslint was complaining about code complexity - what's a good strategy to get around it? 
Anyway, here it is -- numberToString(Number) String
Converts a positive integer up to 2^53-1 to its English string representation.
=> feat: convers a number to string representation

src/index.js, src/removeElementByIndex.js, test/removeElementByIndex.test.js
I added `removeElementByIndex` function
=> Added `removeElementByIndex` function

src/array-multiplier.js, src/index.js, test/array-multiplier.test.js
Have added the Array multiplier feature. Let us merge now.
=> feat(arrMultiplier): add multiplier to Array
